
/* Drop Tables */

DROP TABLE TAG_RELATION;
DROP TABLE BOOK;
DROP TABLE TAG;




/* Create Tables */

CREATE TABLE BOOK
(
	BOOK_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ISBN TEXT,
	TITLE TEXT,
	TITLE_KANA TEXT,
	AUTHOR TEXT,
	AUTHOR_KANA TEXT,
	PUBLISHER_NAME TEXT,
	SALES_DATE REAL,
	IMAGE NONE,
	PRIMARY KEY (BOOK_ID)
);


CREATE TABLE TAG
(
	TAG_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	USER_TAG_FLAG INTEGER DEFAULT 1 NOT NULL CHECK IN (0, 1),
	PRIMARY KEY (TAG_ID),
	CONSTRAINT CNST_TAG_RELATION UNIQUE (NAME, USER_TAG_FLAG)
);


CREATE TABLE TAG_RELATION
(
	_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	TAG_ID INTEGER NOT NULL UNIQUE,
	BOOK_ID INTEGER NOT NULL UNIQUE,
	PRIMARY KEY (_ID),
	FOREIGN KEY (TAG_ID)
	REFERENCES TAG (TAG_ID),
	FOREIGN KEY (BOOK_ID)
	REFERENCES BOOK (BOOK_ID)
);



